### PR TITLE
Support for array types

### PR DESCRIPTION
**Pull request by alexjesp**
## Context

In PostgreSQL you can have array types e.g. for `tags` below
```dbml
Table ticket {
  id String [pk]
  subject String [not null]
  tags String[] [not null]
}
```

The current version of dbml-renderer gives me the following error when trying to generate an SVG from this

```
Could not parse input at line 12:17. Expected "//", "}", space, or whitespace but "[" found.
```

## Reproduction

Using https://github.com/notiz-dev/prisma-dbml-generator to output DBML from a Prisma schema file can give something like the following:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}

generator dbml {
  provider = "prisma-dbml-generator"
  includeRelationFields = false
}

datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

model Ticket {
  id        String      @id
  subject   String
  tags      String[]

  @@map("ticket")
}
```

Outputs the following DBML file:

```dbml
Table ticket {
  id String [pk]
  subject String [not null]
  tags String[] [not null]
}
```
Which gives the error above.

## Related Issues

- Fixes https://github.com/softwaretechnik-berlin/dbml-renderer/issues/27
- Fixes https://github.com/softwaretechnik-berlin/dbml-renderer/issues/28

### CODE REVIEW

**Review by asfaltboy — APPROVED** [review]
let's goooo! 🎸 🚀

**Comment by barnardb** [comment]
Nice.

Looking at https://www.postgresql.org/docs/current/arrays.html, it seems that there are also multidimensional arrays, and that exact sizes can be specified. E.g., here's an example from that page:
```sql
CREATE TABLE tictactoe (
    squares   integer[3][3]
);
```

There's also an alternative syntax with the `ARRAY` keyword.

So perhaps we could extend the example to something like this:
```dbml
Table user {
    id integer [primary key, increment]
    tags varchar[]
    favorite_colors varchar ARRAY[]
    friend_groups uuid[][]
    position double precision[3]
    orientation_quaternion double precision ARRAY[4]
}
```

**Comment by barnardb** [comment]
I tried out my extended example on https://dbdiagram.io/d, and it doesn't like either the ARRAY syntax (and now that I think about it, why should it—this is DBML, not SQL) and it doesn't like the fixed array lengths. So maybe we should just make sure that we support multidimensional arrays, and leave the rest for now. I.e.:
```dbml
Table user {
    id integer [primary key, increment]
    tags varchar[]
    friend_groups uuid[][]
}
```

**Comment by barnardb** [comment]
We ended up supporting
```dbml
Table user {
    id integer [primary key, increment]
    tags varchar[]
    friend_groups uuid[][]
    position decimal(3,5)[3]
}
```

If someone really wants the `ARRAY` clutter, they can always quote the type (e.g. `foo "double precision ARRAY[]"`).

**Pull request merged**
